'use client';

import React, { createContext, useContext, useState, ReactNode, useEffect } from 'react';

type Language = 'RU' | 'EN';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, variables?: Record<string, string | number>) => string;
}

const translations: Record<Language, Record<string, string>> = {
  RU: {
    'nav.stock': 'Склад',
    'nav.wp-products': 'Товары',
    'nav.assembly': 'Сборка',
    'nav.purchases': 'Закупки',
    'nav.showcase': 'Витрина',
    'nav.analytics': 'Аналитика',
    'nav.expenses': 'Расходы',
    'header.online': 'Онлайн',
    'role.owner': 'Владелец (Все цены)',
    'role.accountant': 'Бухгалтер (Все цены)',
    'role.employee': 'Сотрудник (Только розница)',
    'role.only.owner': 'Владелец',
    'role.only.admin': 'Администратор',
    'role.only.accountant': 'Бухгалтер',
    'role.only.employee': 'Сотрудник',
    'action.export': 'Экспорт QB',
    'action.add': 'Добавить',
    'action.save': 'Сохранить',
    'action.delete': 'Удалить',
    'action.edit': 'Редактировать',
    'stock.title': 'Складские Запасы',
    'stock.subtitle': 'Текущее состояние цветов и материалов',
    'stock.loading': 'Загрузка склада...',
    'stock.low': 'Низкий запас',
    'stock.left': 'осталось',
    'stock.reserved': 'Сырье в резерве',
    'stock.barcode': 'Сканировать штрих-код',
    'stock.categories': 'Категории',
    'stock.zero_items': 'ноль позиций',
    'table.sku': 'Артикул',
    'table.name': 'Название',
    'table.category': 'Категория',
    'table.balance': 'Остаток',
    'table.units': 'Единицы',
    'table.cost': 'Цена закупки',
    'table.retail': 'Розница',
    'table.actions': 'Действия',
    'assembly.title': 'Сборка Букетов',
    'assembly.subtitle': 'Новый букет и списание материалов',
    'assembly.worker': 'Сотрудник (Сборщик)',
    'assembly.name': 'Название букета',
    'assembly.name_placeholder': 'Напр., Весенний рассвет',
    'assembly.price': 'Розничная цена продажи',
    'assembly.photo': 'URL фото (необязательно)',
    'assembly.photo_placeholder': 'https://...',
    'assembly.materials': 'Использованные материалы',
    'assembly.materials_desc': 'Выберите цветы и упаковку, которые ушли на этот букет',
    'assembly.select_material': '-- Выберите материал --',
    'assembly.qty': 'Кол-во',
    'assembly.add_material': 'Добавить материал',
    'assembly.create': 'Собрать букет',
    'assembly.history': 'История Сборок',
    'assembly.history_desc': 'Последние собранные букеты',
    'assembly.loading': 'Загрузка истории и склада...',
    'purchases.title': 'Закупки & Поступления',
    'purchases.subtitle': 'Регистрация новых партий товара',
    'purchases.loading': 'Загрузка истории закупок...',
    'purchases.supplier': 'Поставщик',
    'purchases.supplier_placeholder': 'Напр. Эквадор Фарм',
    'purchases.invoice': 'Номер накладной (опционально)',
    'purchases.items': 'Товары в партии',
    'purchases.items_desc': 'Выберите существующий товар или введите новый',
    'purchases.select_product': '-- Выберите товар --',
    'purchases.cost_price': 'Цена закупки',
    'purchases.retail_price': 'Розничная цена (если меняется)',
    'purchases.add_item': 'Добавить товар в накладную',
    'purchases.total': 'Итого по накладной: {total}',
    'purchases.register': 'Зарегистрировать партию',
    'purchases.history': 'История Закупок',
    'purchases.history_desc': 'Недавние поступления на склад',
    'purchases.date': 'Дата',
    'purchases.total_table': 'Сумма',
    'purchases.suppliers': 'Поставщики',
    'status.in_transit': 'в дороге',
    'status.delivered': 'доставлена',
    'status.received': 'получена',
    'analytics.title': 'Финансовая Аналитика',
    'analytics.subtitle': 'Основные показатели бизнеса',
    'analytics.loading': 'Загрузка аналитики...',
    'analytics.revenue': 'Выручка',
    'analytics.revenue_desc': 'за последние 30 дней',
    'analytics.profit': 'Маржинальная прибыль',
    'analytics.profit_desc': 'расчетная от продаж',
    'analytics.top_product': 'Топ продаж',
    'analytics.top_product_desc': 'самый популярный товар',
    'analytics.sales_chart': 'Динамика Продаж (тест)',
    'analytics.chart_desc': 'Визуализация выручки по дням',
    'analytics.report_desc': 'Детальный отчет по продажам и остаткам',
    'analytics.range_today': 'Сегодня',
    'analytics.range_week': '7 дней',
    'analytics.range_month': '30 дней',
    'analytics.range_year': 'Год',
    'analytics.range_custom': 'Свой период',
    'analytics.range_all': 'Все время',
    'analytics.filter_category': 'Категория товара',
    'analytics.filter_cat_all': 'Все категории',
    'analytics.filter_product': 'Конкретный товар',
    'analytics.filter_prod_all': 'Все товары (Общий учет)',
    'analytics.filter_supplier': 'Поставщик',
    'analytics.filter_sup_all': 'Все поставщики',
    'analytics.filter_sup_none': 'Без поставщика',
    'analytics.reset': 'Сбросить',
    'analytics.total_revenue': 'Общая Выручка',
    'analytics.website': 'Сайт',
    'analytics.physical_store': 'Розничная точка',
    'analytics.sales_amount': 'Сумма продаж',
    'analytics.snapshot': 'Снимок Склада',
    'analytics.total_items': 'Всего позиций',
    'analytics.retail_potential': 'Розничный потенциал',
    'analytics.popular': 'Популярные товары',
    'analytics.sold': 'прод.',
    'analytics.writeoffs_log': 'Журнал списаний и брака',
    'analytics.records_count': 'Кол-во актов',
    'analytics.cost_losses': 'Потери по закупке',
    'analytics.lost_profit': 'Упущенная выгода',
    'analytics.date': 'Дата',
    'analytics.employee': 'Сотрудник',
    'analytics.loss_amount': 'Сумма потерь',
    'analytics.details': 'Подробности / Описание',
    'analytics.reason': 'Причина списания',
    'analytics.btn_details': 'Подробнее',
    'analytics.showcase_sales': 'Продажи с витрины',
    'analytics.detailed_website_sales': 'Продажи на сайте подробно',
    'analytics.combined_revenue': 'Общая выручка',
    'analytics.writeoffs_losses': 'Списание и потери',
    'analytics.popular_products': 'Популярные товары',
    'analytics.no_sales_data': 'Нет данных о продажах за этот период',
    'analytics.online_orders': 'Заказы с сайта',
    'analytics.export_excel': 'Экспорт в Excel',
    'analytics.exporting': 'Формируем...',
    'showcase.title': 'Витрина',
    'showcase.subtitle': 'Управление готовыми букетами',
    'showcase.loading': 'Загрузка витрины...',
    'showcase.sell': 'Продать',
    'showcase.decompose': 'Разобрать / Списать',
    'showcase.empty': 'На витрине пока нет букетов',
    'reason.Theft': 'Кража',
    'reason.TransportDamage': 'Повреждение при транспортировке',
    'reason.Expired': 'Истекший срок годности',
    'reason.Defective': 'Брак / дефект',
    'reason.Shortage': 'Недостача',
    'reason.Obsolete': 'Устаревший товар',
    'reason.Lost': 'Утеря товара',
    'reason.Damaged': 'Поврежденный товар',
    'reason.SupplierReturn': 'Возврат поставщику',
    'reason.ProductionWaste': 'Производственные потери',
    'reason.Disaster': 'Повреждение из-за стихийного бедствия',
    'reason.AdminWriteOff': 'Административное списание',
    'reason.QualityFailure': 'Несоответствие контролю качества',
    'reason.Spoilage': 'Порча товара',
    'reason.BadStorage': 'Неправильные условия хранения',
    'reason.PromoGiveaway': 'Промо-подарок',
    'reason.GiftToCustomer': 'Подарок клиенту',
    'reason.Complimentary': 'Бесплатно предоставленный товар',
    'reason.FOC': 'Бесплатно',
    'reason.Marketing': 'Маркетинг',
    'reason.PromoWriteOff': 'Списание в рекламных целях',
    'reason.GiftWriteOff': 'Списание как подарок',
    'reason.CUSTOM': 'Другое (вписать свое)',
    'analytics.financial_metrics_by_channel': 'Финансовые показатели по каналам продаж',
    'analytics.online_sales': 'Продажи на сайте',
    'analytics.revenue_label': 'Выручка',
    'analytics.cost_price_label': 'Цена закупки',
    'analytics.profit_label': 'Прибыль',
    'analytics.net_profit_label': 'Чистая Прибыль',
    'analytics.margin_label': 'Маржинальность',
    'analytics.total_margin_label': 'Общая рентабельность',
    'analytics.total_cost_label': 'Суммарная цена закупки',
    'analytics.lost_revenue_label': 'Упущенная Выручка',
    'analytics.cost_loss_label': 'Убыток (Цена закупки)',
    'analytics.writeoffs_count_label': 'Количество списаний',
    'analytics.cost_ratio_label': 'Доля от цены зак. продаж',
    'analytics.total_badge': 'Итог',
    'analytics.losses_badge': 'Потери',
    'analytics.units_qty': 'ед.',
    'analytics.pieces': 'шт.',
    'analytics.pieces_in_stock': 'шт на складе',
    'analytics.low_stock_warn': 'мало!',
    'analytics.warehouse_free': 'Склад (свободно)',
    'analytics.raw_reserve': 'Сырье в резерве',
    'analytics.no_writeoffs': 'Нет записей о списаниях за выбранный период.',
    'analytics.writeoff_type': 'Тип списания',
    'analytics.writeoff_nomenclature': 'Номенклатура',
    'analytics.writeoff_qty': 'Кол-во',
    'analytics.type_warehouse_raw': 'Сырье со склада',
    'analytics.type_showcase_defect': 'Брак на витрине',
    'analytics.delete_writeoff': 'Удалить',
    'analytics.cancel_writeoff_title': 'Отменить списание и вернуть на остаток',
    'analytics.modal_showcase_bouquets': '💐 Букеты на витрине',
    'analytics.modal_showcase_bouquets_count': '💐 Букеты на витрине ({count})',
    'analytics.modal_website_sales': '🌐 Заказы с сайта',
    'analytics.modal_website_sales_count': '🌐 Заказы с сайта ({count})',
    'analytics.modal_raw_warehouse': '📦 Сырье на складе',
    'analytics.modal_raw_warehouse_count': '📦 Сырье на складе ({count})',
    'analytics.modal_showcase_empty': '💐 Букетов на витрине пока нет.',
    'analytics.modal_available': '🟢 На витрине',
    'analytics.modal_reserved': '🔒 Забронирован',
    'analytics.modal_composition': 'Состав букета:',
    'analytics.modal_created': 'Создан:',
    'analytics.modal_created_at': 'в',
    'analytics.modal_loading_orders': 'Загрузка активных заказов...',
    'analytics.modal_no_orders': '🌐 Нет активных заказов (в обработке/ожидании) на сайте WooCommerce.',
    'analytics.modal_order_num': 'Заказ #{id}',
    'analytics.modal_client': 'Клиент:',
    'analytics.modal_date': 'Дата:',
    'analytics.modal_order_items': 'Товары в заказе:',
    'analytics.modal_no_raw_reserved': '📦 Зарезервированного сырья на складе нет.',
    'analytics.modal_sku': 'Артикул:',
    'analytics.modal_category': 'Категория:',
    'analytics.modal_retail_value': 'Розничная стоимость:',
    'analytics.modal_close': 'Закрыть',
  },
  EN: {
    'nav.stock': 'Stock',
    'nav.wp-products': 'Products',
    'nav.assembly': 'Assembly',
    'nav.purchases': 'Purchases',
    'nav.showcase': 'Showcase',
    'nav.analytics': 'Analytics',
    'nav.expenses': 'Expenses',
    'header.online': 'Online',
    'role.owner': 'Owner (All prices)',
    'role.accountant': 'Accountant (All prices)',
    'role.employee': 'Employee (Retail only)',
    'role.only.owner': 'Owner',
    'role.only.admin': 'Admin',
    'role.only.accountant': 'Accountant',
    'role.only.employee': 'Employee',
    'action.export': 'Export QB',
    'action.add': 'Add',
    'action.save': 'Save',
    'action.delete': 'Delete',
    'action.edit': 'Edit',
    'stock.title': 'Inventory',
    'stock.subtitle': 'Current status of flowers and materials',
    'stock.loading': 'Loading inventory...',
    'stock.low': 'Low stock',
    'stock.left': 'left',
    'stock.reserved': 'Raw materials in reserve',
    'stock.barcode': 'Scan barcode',
    'stock.categories': 'Categories',
    'stock.zero_items': '0 items',
    'table.sku': 'SKU',
    'table.name': 'Name',
    'table.category': 'Category',
    'table.balance': 'Balance',
    'table.units': 'Units',
    'table.cost': 'Purchase Price',
    'table.retail': 'Retail Price',
    'table.actions': 'Actions',
    'assembly.title': 'Bouquet Assembly',
    'assembly.subtitle': 'New bouquet and material deduction',
    'assembly.worker': 'Employee (Assembler)',
    'assembly.name': 'Bouquet Name',
    'assembly.name_placeholder': 'E.g., Spring Dawn',
    'assembly.price': 'Retail Sale Price',
    'assembly.photo': 'Photo URL (optional)',
    'assembly.photo_placeholder': 'https://...',
    'assembly.materials': 'Materials Used',
    'assembly.materials_desc': 'Select flowers and packaging used for this bouquet',
    'assembly.select_material': '-- Select Material --',
    'assembly.qty': 'Qty',
    'assembly.add_material': 'Add Material',
    'assembly.create': 'Assemble Bouquet',
    'assembly.history': 'Assembly History',
    'assembly.history_desc': 'Recently assembled bouquets',
    'assembly.loading': 'Loading history and stock...',
    'purchases.title': 'Purchases & Receipts',
    'purchases.subtitle': 'Register new incoming shipments',
    'purchases.loading': 'Loading purchase history...',
    'purchases.supplier': 'Supplier',
    'purchases.supplier_placeholder': 'E.g. Ecuador Farms',
    'purchases.invoice': 'Invoice Number (Optional)',
    'purchases.items': 'Items in Shipment',
    'purchases.items_desc': 'Select an existing product or enter a new one',
    'purchases.select_product': '-- Select Product --',
    'purchases.cost_price': 'Purchase Price',
    'purchases.retail_price': 'Retail Price (if modifying)',
    'purchases.add_item': 'Add Item to Invoice',
    'purchases.total': 'Total for Invoice: {total}',
    'purchases.register': 'Register Shipment',
    'purchases.history': 'Purchase History',
    'purchases.history_desc': 'Recent stock arrivals',
    'purchases.date': 'Date',
    'purchases.total_table': 'Total',
    'purchases.suppliers': 'Suppliers',
    'status.in_transit': 'in transit',
    'status.delivered': 'delivered',
    'status.received': 'received',
    'analytics.title': 'Financial Analytics',
    'analytics.subtitle': 'Key Business Metrics',
    'analytics.loading': 'Loading analytics...',
    'analytics.revenue': 'Revenue',
    'analytics.revenue_desc': 'last 30 days',
    'analytics.profit': 'Gross Profit',
    'analytics.profit_desc': 'estimated from sales',
    'analytics.top_product': 'Top Sale',
    'analytics.top_product_desc': 'most popular item',
    'analytics.sales_chart': 'Sales Dynamics (test)',
    'analytics.chart_desc': 'Revenue visualization by day',
    'analytics.report_desc': 'Detailed report on sales and inventory',
    'analytics.range_today': 'Today',
    'analytics.range_week': '7 days',
    'analytics.range_month': '30 days',
    'analytics.range_year': 'Year',
    'analytics.range_custom': 'Custom range',
    'analytics.range_all': 'All time',
    'analytics.filter_category': 'Product Category',
    'analytics.filter_cat_all': 'All Categories',
    'analytics.filter_product': 'Specific Product',
    'analytics.filter_prod_all': 'All Products (Total)',
    'analytics.filter_supplier': 'Supplier',
    'analytics.filter_sup_all': 'All Suppliers',
    'analytics.filter_sup_none': 'No Supplier',
    'analytics.reset': 'Reset',
    'analytics.total_revenue': 'Total Revenue',
    'analytics.website': 'Website',
    'analytics.physical_store': 'Physical Store',
    'analytics.sales_amount': 'Sales Amount',
    'analytics.snapshot': 'Inventory Snapshot',
    'analytics.total_items': 'Total items',
    'analytics.retail_potential': 'Retail potential',
    'analytics.popular': 'Popular Products',
    'analytics.sold': 'sold',
    'analytics.writeoffs_log': 'Write-offs & Defects Log',
    'analytics.records_count': 'Number of records',
    'analytics.cost_losses': 'Cost losses',
    'analytics.lost_profit': 'Lost profit',
    'analytics.date': 'Date',
    'analytics.employee': 'Employee',
    'analytics.loss_amount': 'Loss Amount',
    'analytics.details': 'Details / Description',
    'analytics.reason': 'Reason for write-off',
    'analytics.btn_details': 'Details',
    'analytics.showcase_sales': 'Showcase Sales',
    'analytics.detailed_website_sales': 'Detailed Website Sales',
    'analytics.combined_revenue': 'Total Revenue',
    'analytics.writeoffs_losses': 'Write-offs & Losses',
    'analytics.popular_products': 'Popular Products',
    'analytics.no_sales_data': 'No sales data for this period',
    'analytics.online_orders': 'Website Sales',
    'analytics.export_excel': 'Export to Excel',
    'analytics.exporting': 'Generating...',
    'showcase.title': 'Showcase',
    'showcase.subtitle': 'Manage finished bouquets',
    'showcase.loading': 'Loading showcase...',
    'showcase.sell': 'Sell',
    'showcase.decompose': 'Decompose / Defect',
    'showcase.empty': 'Showcase is empty',
    'reason.Theft': 'Theft / Stolen goods',
    'reason.TransportDamage': 'Damage during transportation',
    'reason.Expired': 'Expired goods',
    'reason.Defective': 'Defective items',
    'reason.Shortage': 'Inventory shortage',
    'reason.Obsolete': 'Obsolete inventory',
    'reason.Lost': 'Lost items',
    'reason.Damaged': 'Damaged goods',
    'reason.SupplierReturn': 'Supplier return',
    'reason.ProductionWaste': 'Production waste',
    'reason.Disaster': 'Natural disaster damage',
    'reason.AdminWriteOff': 'Administrative write-off',
    'reason.QualityFailure': 'Quality control failure',
    'reason.Spoilage': 'Spoilage',
    'reason.BadStorage': 'Incorrect storage conditions',
    'reason.PromoGiveaway': 'Promotional giveaway',
    'reason.GiftToCustomer': 'Gift to customer',
    'reason.Complimentary': 'Complimentary item',
    'reason.FOC': 'Free of charge (FOC)',
    'reason.Marketing': 'Marketing',
    'reason.PromoWriteOff': 'Write-off for promotional purposes',
    'reason.GiftWriteOff': 'Gift write-off',
    'reason.CUSTOM': 'Other (Custom reason)',
    'analytics.financial_metrics_by_channel': 'Financial metrics by sales channel',
    'analytics.online_sales': 'Website Sales',
    'analytics.revenue_label': 'Revenue',
    'analytics.cost_price_label': 'Purchase Price',
    'analytics.profit_label': 'Profit',
    'analytics.net_profit_label': 'Net Profit',
    'analytics.margin_label': 'Margin',
    'analytics.total_margin_label': 'Total Profit Margin',
    'analytics.total_cost_label': 'Total Purchase Cost',
    'analytics.lost_revenue_label': 'Lost Revenue',
    'analytics.cost_loss_label': 'Cost Loss (Purchase Price)',
    'analytics.writeoffs_count_label': 'Number of Write-offs',
    'analytics.cost_ratio_label': 'Share of Purchase Cost',
    'analytics.total_badge': 'Total',
    'analytics.losses_badge': 'Losses',
    'analytics.units_qty': 'pcs.',
    'analytics.pieces': 'pcs.',
    'analytics.pieces_in_stock': 'pcs in stock',
    'analytics.low_stock_warn': 'low!',
    'analytics.warehouse_free': 'Warehouse (available)',
    'analytics.raw_reserve': 'Raw materials in reserve',
    'analytics.no_writeoffs': 'No write-off records for the selected period.',
    'analytics.writeoff_type': 'Write-off Type',
    'analytics.writeoff_nomenclature': 'Nomenclature',
    'analytics.writeoff_qty': 'Qty',
    'analytics.type_warehouse_raw': 'Warehouse Raw materials',
    'analytics.type_showcase_defect': 'Showcase Defect',
    'analytics.delete_writeoff': 'Delete',
    'analytics.cancel_writeoff_title': 'Cancel write-off and return to stock',
    'analytics.modal_showcase_bouquets': '💐 Showcase Bouquets',
    'analytics.modal_showcase_bouquets_count': '💐 Showcase Bouquets ({count})',
    'analytics.modal_website_sales': '🌐 Website Orders',
    'analytics.modal_website_sales_count': '🌐 Website Orders ({count})',
    'analytics.modal_raw_warehouse': '📦 Raw materials in stock',
    'analytics.modal_raw_warehouse_count': '📦 Raw materials in stock ({count})',
    'analytics.modal_showcase_empty': '💐 Showcase is currently empty.',
    'analytics.modal_available': '🟢 Showcase',
    'analytics.modal_reserved': '🔒 Reserved',
    'analytics.modal_composition': 'Bouquet Composition:',
    'analytics.modal_created': 'Created:',
    'analytics.modal_created_at': 'at',
    'analytics.modal_loading_orders': 'Loading active orders...',
    'analytics.modal_no_orders': '🌐 No active orders (processing/pending) on WooCommerce website.',
    'analytics.modal_order_num': 'Order #{id}',
    'analytics.modal_client': 'Client:',
    'analytics.modal_date': 'Date:',
    'analytics.modal_order_items': 'Items in order:',
    'analytics.modal_no_raw_reserved': '📦 No reserved raw materials in stock.',
    'analytics.modal_sku': 'SKU:',
    'analytics.modal_category': 'Category:',
    'analytics.modal_retail_value': 'Retail value:',
    'analytics.modal_close': 'Close',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>('RU');

  useEffect(() => {
    const saved = localStorage.getItem('language');
    if (saved === 'RU' || saved === 'EN') {
      setLanguageState(saved);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string, variables?: Record<string, string | number>) => {
    let str = translations[language][key] || key;
    if (variables) {
      for (const [k, v] of Object.entries(variables)) {
        str = str.replace(`{${k}}`, String(v));
      }
    }
    return str;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
